# Generated by Django 5.1.3 on 2024-11-23 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0005_remove_cuenta_usuario'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cuenta',
            field=models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='Cuenta', to='transacciones.cuenta'),
            preserve_default=False,
        ),
    ]
