# Generated by Django 5.1.3 on 2024-11-24 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuariofavorito'),
        ('usuarios', '0006_alter_transferencia_motivo'),
    ]

    operations = [
    ]
