# Generated by Django 5.1.3 on 2024-11-21 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='tipo',
            field=models.CharField(choices=[('ingreso', 'Ingreso'), ('transferencia', 'Transferencia'), ('ingresotransferencia', 'Ingreso  por Transferencia')], max_length=20),
        ),
    ]
