# Generated by Django 5.1.3 on 2024-11-22 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0002_alter_movimiento_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='tipo',
            field=models.CharField(choices=[('ingreso', 'Ingreso'), ('transferencia', 'Transferencia'), ('ingresotransferencia', 'Ingreso  por Transferencia')], max_length=30),
        ),
    ]
