# Generated by Django 5.1.3 on 2024-11-22 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0003_alter_movimiento_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='cuenta_movimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuenta', to='transacciones.cuenta'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='cuenta_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_destino', to='transacciones.cuenta'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='cuenta_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_origen', to='transacciones.cuenta'),
        ),
    ]
