# Generated by Django 5.1.3 on 2024-11-23 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0004_movimiento_cuenta_movimiento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuenta',
            name='usuario',
        ),
    ]
