# Generated by Django 5.1.3 on 2024-11-23 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0006_cuenta_usuario'),
        ('usuarios', '0006_alter_transferencia_motivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='motivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.motivotransferencia'),
        ),
        migrations.DeleteModel(
            name='MotivoTransferencia',
        ),
    ]
